const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.tokencount,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Solid: 0},
	{ground: 0},
	{tree: 0},
	{key_processed: 0},
	{invincible: 0},
	{Piscar: 0},
	{samurai: 0},
	{sequence: 0},
	{progress: 0},
	{arrows_created: 0},
	{Bullet: 0},
	{enemy: 0},
	{sequence_text: 0},
	{keyboard: 0},
	{debug_text: 0},
	{lives_text: 0},
	{game_over_text: 0},
	{sequences_list: 0},
	{side: 0},
	{Timer: 0},
	{spawner: 0},
	{score_text: 0},
	{leaves_particles: 0},
	{title_text: 0},
	{play_button: 0},
	{mouse: 0},
	{play_text: 0},
	{play_again_button: 0},
	{play_again_text: 0},
	{arrow_index: 0},
	{Fixar: 0},
	{directional_arrow: 0},
	{heart_id: 0},
	{Flash: 0},
	{heart: 0},
	{audio: 0},
	{Fade: 0},
	{fade_transition: 0},
	{slach: 0},
	{death_particles: 0},
	{game_victory_text: 0},
	{target_UID: 0},
	{lives: 0},
	{game_over: 0},
	{score: 0},
	{enemy_velocity: 0},
	{sequence_length: 0},
	{score_increase_rate: 0},
	{game_victory: 0}
];

self.InstanceType = {
	background: class extends self.ITiledBackgroundInstance {},
	ground: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	samurai: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	sequence_text: class extends self.ITextInstance {},
	keyboard: class extends self.IInstance {},
	debug_text: class extends self.ITextInstance {},
	lives_text: class extends self.ITextInstance {},
	game_over_text: class extends self.ITextInstance {},
	sequences_list: class extends self.IArrayInstance {},
	spawner: class extends self.ISpriteInstance {},
	score_text: class extends self.ITextInstance {},
	leaves_particles: class extends self.IParticlesInstance {},
	title_text: class extends self.ITextInstance {},
	play_button: class extends self.ISpriteInstance {},
	mouse: class extends self.IInstance {},
	play_text: class extends self.ITextInstance {},
	play_again_button: class extends self.ISpriteInstance {},
	play_again_text: class extends self.ITextInstance {},
	directional_arrow: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	audio: class extends self.IInstance {},
	fade_transition: class extends self.ITiledBackgroundInstance {},
	slach: class extends self.ISpriteInstance {},
	death_particles: class extends self.IParticlesInstance {},
	game_victory_text: class extends self.ITextInstance {}
}